name: "Unit Tests"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install test suite dependencies
        run: |
          python -m pip install .[tests]
          python -m pip install qa/tools
          python -m pip install -r qa/unittests/requirements.txt
      - name: Run pytest on esa_apex_toolbox
        run: |
          pytest
      - name: Run pytest on qa/unittests
        run: |
          cd qa/unittests
          pytest
